version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/config:/config
      - /tmp/:/transcode
      - /tank/media:/data
