version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    network_mode: "host"
    environment:
      - PUID=1003
      - PGID=1003
    volumes:
      - /home/plex:/config
      - /tmp/:/transcode
      - /tank/media:/data
